version: "3"

networks:
  nats_monitoring_network:
    driver: bridge

services:

  nats-server:
    command:
      - "-p"
      - "4222"
      - "-m"
      - "8222"
      - "-js"
      # - "-c=/opt/run/simple-server.conf" # config file to change auth with user and pass 
      - "-auth"
      - ${NATS_AUTH_TOKEN}
      - "--debug"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/:/opt/run/
      - /tmp/docker-shared-volumes/nats:/tmp/nats/jetstream
      # - ./nats/entrypoint.sh:/opt/run/entrypoint.sh
    # entrypoint: ["/bin/sh", "/opt/run/entrypoint.sh"]
    image: nats:alpine3.19 # use alpine, able to exec the container
    # image: nats:latest
    container_name: nats-server
    networks:
      - nats_monitoring_network
    env_file:
      - .env
    labels:
      org.label-schema.group: "nats-monitoring"

  prometheus-nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    ports:
      - "7778:7777"
    environment:
      - NATS_URL=${NATS_URL}
    networks:
      - nats_monitoring_network
    command: -varz -connz -connz_detailed -routez -serverz -channelz -subz -healthz ${NATS_MONITORING_URL}
    depends_on:
      - nats-server

  surveyor:
    image: natsio/nats-surveyor
    container_name: nats-surveyor
    restart: always
    ports:
      - "7777:7777"
    volumes:
      - ./observations:/observations
      - ./jetstream:/jetstream
    entrypoint: /nats-surveyor
    command: -c ${NATS_SURVEYOR_SERVER_COUNT} -s "${NATS_SURVEYOR_SERVERS}" --observe /observations --jetstream /jetstream
    networks:
      - nats_monitoring_network
    env_file:
      - .env
    labels:
      org.label-schema.group: "nats-monitoring"
    depends_on:
      - nats-server

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - nats_monitoring_network
    ports:
      - "9090:9090"
    labels:
      org.label-schema.group: "nats-monitoring"
    depends_on:
      - surveyor
      - prometheus-nats-exporter

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - nats_monitoring_network
    labels:
      org.label-schema.group: "nats-monitoring"
    depends_on:
      - prometheus